### ISSUE TITLE
amankan menyimpan password secara langsung di database ?

### ISSUE THREAD

**Issue by Wongka** [aghanathan/LoginSecurity#1]
salam , 
maaf mas tanya,
saya baru liat file sql yang dikasih sama mas, dan disitu saya lihat password yang masnya buat itu tidak dihash atau encrypt atau apapun lah yang intinya mengamankan .
yang jadi pertanyaannya apakah itu memang sengaja masnya buat seperti itu ?
kalo memang sengaja alasannya apa mas ? karena bukannya tidak aman menyimpan password secara langsung di dalam database ?

**Comment by aghanathan** [comment]
Hay mas @Wongka ,

Terimakasih atas masukannya :)
Sekarang **Project** ini sudah sy tambahkan **_Standard Encryption_** (**md5**)

File yang sudah sy **update** antara lain:
- pada saat **Update User** ('**./Ajax/useractions.php**')
- dan pada saat **Login** pertama kali ('**./index.php**')
- dan juga **Password** pada database SQL nya telah saya rubah ke **md5** ('**./secure.sql**')

Salam Hangat,
**Agah Nataprawira**
